name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Display Chrome version
      run: google-chrome --version

    - name: Restore dependencies
      run: dotnet restore AmazonAutomationTestFramework.sln

    - name: Build solution
      run: dotnet build AmazonAutomationTestFramework.sln --configuration Release --no-restore

    - name: Run tests (NUnit + Selenium headless)
      run: dotnet test AmazonAutomationTestFramework.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/test_results.trx'
